### ISSUE TITLE
how can i set the webview init param ,for example like :  --disable-web-security ; --autoplay-policy=no-user-gesture-required

### ISSUE THREAD

**Issue by fangyuchuang** [webview/webview_java#10]
how can i set the webview init param ,for example like the chromiun can support the  start param :  --disable-web-security ; --autoplay-policy=no-user-gesture-required
that is important for de developer to customized the webview behavor. wish for your reply ,thanks!

**Comment by e3ndr** [comment]
As far as I know, the upstream library does not support this as it's inconsistent across platforms. You may want to investigate other libraries such as Eclipse SWT or JCEFMaven.

**Comment by fangyuchuang** [comment]
thank you, i have resolved it, i make an example in c# by webview2, and i will integrated it to the java.

in c# mainwindow function ,before the InitializeComponent(); call
Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--autoplay-policy=no-user-gesture-required");



At 2023-09-24 14:05:05, "Alex" ***@***.***> wrote:

As far as I know, the upstream library does not support this as it's inconsistent across platforms. You may want to investigate other libraries such as Eclipse SWT or JCEFMaven.
