### ISSUE TITLE
Updated code doesn't compile, missing method

### ISSUE THREAD

**Issue by pagew2000** [webview/webview_java#12]
The code was updated two days ago, but SwingExample.java doesn't even compile, it's calling AWTWebview.setOnInitialized() which doesn't exist.

Tried to create a dummy setOnInitialized() to by-pass the issue to ran SwingExample, but got "java.lang.Error: Invalid memory access" using the provided dll.

Appreciate if the complete/working sample could be provided.

**Comment by e3ndr** [comment]
I'm still working updating the library and making changes. The current supported example for 1.3.0 can be found [here](https://github.com/webview/webview_java/blob/08f944bab9d0a9f10ff416b39bdd443b2d2c12d3/SwingExample.java).

**Comment by pagew2000** [comment]
Thanks! I tried with supported example version, still got "java.lang.Error: Invalid memory access". Looks like the dll version is not correct? (I am using the one from src/main/resources/dev/webview/natives/x86/windows_nt/webview.dll)

**Comment by pagew2000** [comment]
@e3ndr Any update on this issue? I still have the error with the new webview.dll.

**Comment by e3ndr** [comment]
> @e3ndr Any update on this issue? I still have the error with the new webview.dll.

Looks like the newer library is incompatible with AWT for some reason. It appears to be a regression in the upstream library. Still investigating :)

**Comment by e3ndr** [comment]
I've decided to discontinue the AWT component for now.
