### ISSUE TITLE
Jackson and Webview compatibility issue

### ISSUE THREAD

**Issue by YairLevi** [webview/webview_java#13]
I'm trying use this webview lib and jackson together for something, and I found out that the moment I use Jackson somewhere in the code, webview function binds dont work (like the `echo(1,2,3)` from the example).

I believe there is some incompatibility between the two libs, which somewhat makes sense since both jackson and webview binds interact with json related stuff.

Is there a way to fix it without an alternative to Jackson?
and moreover, does anyone else have some knowledge or experienced this issue?

**Comment by e3ndr** [comment]
Can I see the code that you were using?On Dec 29, 2023, at 08:01, YairLevi ***@***.***> wrote:﻿
I'm trying use this webview lib and jackson together for something, and I found out that the moment I use Jackson somewhere in the code, webview function binds dont work (like the echo(1,2,3) from the example).
I believe there is some incompatibility between the two libs, which somewhat makes sense since both jackson and webview binds interact with json related stuff.
Is there a way to fix it without an alternative to Jackson?
and moreover, does anyone else have some knowledge or experienced this issue?

**Comment by YairLevi** [comment]
Yes, of course. forgot to add.

This is for example, code that works, when the `ObjectMapper` from jackson is commented.
```java
public static void main(String[] args) {
//        ObjectMapper om = new ObjectMapper();
        
        Webview wv = new Webview(true);

        wv.bind("echo", (arguments) -> {
            System.out.println(arguments);
            return arguments;
        });

        wv.setTitle("My Webview App");
        wv.setSize(800, 600);
        wv.loadURL("http://localhost:5173");
        wv.run();
    }
```

when I run this, and in the frontend click on a button that triggers `window["echo"]`, it prints `[1,2,3]`.
However, when i simply uncomment the new Objectmapper:
```java
public static void main(String[] args) {
        ObjectMapper om = new ObjectMapper();
        
        Webview wv = new Webview(true);

        wv.bind("echo", (arguments) -> {
            System.out.println(arguments);
            return arguments;
        });

        wv.setTitle("My Webview App");
        wv.setSize(800, 600);
        wv.loadURL("http://localhost:5173");
        wv.run();
    }
```

it just stops working, and the function `echo` doesnt execute. even though on `console.log(window)`, it shows that the function is a part of window.

**Comment by e3ndr** [comment]
> Yes, of course. forgot to add.
> 
> This is for example, code that works, when the `ObjectMapper` from jackson is commented.
> 
> ```java
> public static void main(String[] args) {
> //        ObjectMapper om = new ObjectMapper();
>         
>         Webview wv = new Webview(true);
> 
>         wv.bind("echo", (arguments) -> {
>             System.out.println(arguments);
>             return arguments;
>         });
> 
>         wv.setTitle("My Webview App");
>         wv.setSize(800, 600);
>         wv.loadURL("http://localhost:5173");
>         wv.run();
>     }
> ```
> 
> when I run this, and in the frontend click on a button that triggers `window["echo"]`, it prints `[1,2,3]`. However, when i simply uncomment the new Objectmapper:
> 
> ```java
> public static void main(String[] args) {
>         ObjectMapper om = new ObjectMapper();
>         
>         Webview wv = new Webview(true);
> 
>         wv.bind("echo", (arguments) -> {
>             System.out.println(arguments);
>             return arguments;
>         });
> 
>         wv.setTitle("My Webview App");
>         wv.setSize(800, 600);
>         wv.loadURL("http://localhost:5173");
>         wv.run();
>     }
> ```
> 
> it just stops working, and the function `echo` doesnt execute. even though on `console.log(window)`, it shows that the function is a part of window.

I'm not aware of any incompatibilities with Jackson. In this latest version though, I did remove the Rson dependency all together. Could you try using the latest commit?
