### ISSUE TITLE
webview.eval() doesnt work when string contains java variables

### ISSUE THREAD

**Issue by YairLevi** [webview/webview_java#16]
after calling `run()`, and waiting for the page to load, 
i have a bind method that calls `eval()`. but `eval()` doesnt execute on the frontend if i add a parameter as part of the string argument that `eval()` receives. here is code to reproduce:

```java
       // This code doesn't work, the frontend doesn't log anything, not even an error.
        wv.bind("echo", jsonElements -> {
            String s = "hello world";
            wv.eval("console.log('"+s+"');");
            return jsonElements;
        });

       // This code works perfectly.
        wv.bind("echo", jsonElements -> {
            wv.eval("console.log('hello world');");
            return jsonElements;
        });
```

it seems like raw strings work but parameters break something. any idea why that is?

**Comment by e3ndr** [comment]
Seems like you might be creating invalid JavaScript with the addition of that. Does this work?
`wv.eval("console.log("+s+");");`

**Comment by YairLevi** [comment]
> Seems like you might be creating invalid JavaScript with the addition of that. Does this work? `wv.eval("console.log("+s+");");`

Thanks for the reply. Turns out my problem was that I binded the "echo" method after the line `wv.loadURL()`, so it didn't even register to begin with. Just noticed it right now, someone mentioned that in the Go wrapper to webview.
I was a little hasty on that one. I'll close this issue. If anyone else faces this problem, make sure to run `loadURL()` right before `run()` to avoid such occurrences.

**Comment by e3ndr** [comment]
> > Seems like you might be creating invalid JavaScript with the addition of that. Does this work? `wv.eval("console.log("+s+");");`
> 
> Thanks for the reply. Turns out my problem was that I binded the "echo" method after the line `wv.loadURL()`, so it didn't even register to begin with. Just noticed it right now, someone mentioned that in the Go wrapper to webview. I was a little hasty on that one. I'll close this issue. If anyone else faces this problem, make sure to run `loadURL()` right before `run()` to avoid such occurrences.

Yeah, run() causes the current thread to block indefinitely. So bind() will never get called until the webview closes.
