### ISSUE TITLE
Bound java methods stop being called if one of them recursively iterates through the file system?

### ISSUE THREAD

**Issue by newk5** [webview/webview_java#17]
Ok so this issue is pretty weird, but I've noticed if one of my bound methods ( set up through webview.bind ) recursively iterates through the file system, all other methods that I've bound with webview.bind stop being called. I know it sounds crazy but it's happening. Here's some code to reproduce:

```java
    static int foldersCounted = 0;
    static int folderCountLimit = 8000;

    public static void main(String[] args) throws InterruptedException {

        Webview wv = new Webview(true);

        wv.bind("test", (arguments) -> {
            System.out.println("test called");
            return null;
        });

        wv.bind("onPageReady", (arguments) -> {
            System.out.println("onPageReady called");
            long start = System.currentTimeMillis();
            countFolders(new File("C:\\"));
            long end = System.currentTimeMillis();

            System.out.println("done " + (end - start));
            return null;
        });

        wv.setTitle("My Webview App");
        wv.setSize(800, 600);

        wv.loadURL("file:///C:/index.html");
        wv.run();
        wv.close();
    }

    private static void countFolders(File dir) {
        if (foldersCounted > folderCountLimit) {
            return;
        }

        File[] lstFiles = dir.listFiles();
        if (lstFiles != null) {
            for (File file : lstFiles) {
                if (file.isDirectory()) {
                    foldersCounted++;
                    countFolders(file);
                }
            }
        }
    }
```

index.html
```html
<!DOCTYPE html>
<html >

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>

<body >
	test
    <script>

        document.addEventListener("DOMContentLoaded", () => {
	    //we wait 500ms for the functions to be bound in java
	   setTimeout(() => {
		onPageReady();
		setTimeout(() => {
		   alert("calling test");
		   test(); //we reach here, but this call never reaches java
		}, 3000);
	   }, 500);
		
        });
    </script>
</body>

</html>

```
The code above calls onPageReady successfully, and 3 seconds later calls the test() function, but this call never reaches java. I've found that if I remove the call to countFolders() on the java side the issue does not happen. It also does not happen if you reduce the value of the variable folderCountLimit to something like 100 or so. If you cant reproduce this issue with the code above, increase the value of folderCountLimit to a high value and you'll eventually be able to reproduce it. Even if I await each call to onPageReady() and test(), the issue still happens. It also happens even when I wrap countFolders() in a new thread.

At first I thought, maybe this is just an issue with the bound method being too slow, so I tried to reproduce the issue just using a Thread.sleep instead of calling countFolders(), but with Thread.sleep the issue never happens, so it seems to be related to something else.

I'm using version 1.3.0

**Comment by newk5** [comment]
I am now noticing more cases in which bound functions are not being called. In some other places in my app I'm doing some db queries and after doing so inside a bound function (even if inside a new thread), all other bound functions after that stop reaching the java side. So this is likely not related to specifically iterating through the file system as I first thought, but regardless, my code above can be used to consistently reproduce the issue.

**Comment by e3ndr** [comment]
Try using the latest commit and see if the issue is fixed.

**Comment by newk5** [comment]
Is there a snpashot available on jitpack/maven, or do I have to build from source?

**Comment by WanneSimon** [comment]
I've got the same problem.  
I tried  `cpp` code with [webview](https://github.com/webview/webview), 
it works properly.   
So I think it's  caused by `jna` ( `native heap` limited ? ) .

I try to replace `jna` with `jnr` , but `webview_create` doesn't return the corrent pointer value.

**Comment by e3ndr** [comment]
> Is there a snapshot available on jitpack/maven, or do I have to build from source?

Use the latest commit hash as your Version.

**Comment by newk5** [comment]
Ok so I tried the latest commit and can confirm the issue does not happen with the code reproducer I posted above, but it still happens with the code of my real application where instead of recursively counting folders, I'm doing db queries. So the underlying issue is still there.

**Comment by e3ndr** [comment]
> I've got the same problem. I tried `cpp` code with [webview](https://github.com/webview/webview), it works properly. So I think it's caused by `jna` ( `native heap` limited ? ) .
> 
> I try to replace `jna` with `jnr` , but `webview_create` doesn't return the corrent pointer value.

I don't think it's that, because the thread that the code is executing on is originally one created and managed by Java.

**Comment by newk5** [comment]
> Could you try including [Casterlabs Commons/Async](https://github.com/casterlabs/commons) and wrapping your call in a Promise and awaiting it?

Sorry I'm not familiar with that library but I can try it if show me how. I dont understand what you mean, which call? the "test()" call never reaches the java side, are you talking about the first call "onPageReady()" ? But show me an example using the reproducer code I posted above?

**Comment by newk5** [comment]
I just noticed that the reproducer I posted above can still be used to reproduce the problem on the latest commit version if I increase the folderCountLimit from 8000 to 9000.

**Comment by e3ndr** [comment]
I meant this:
```java
        wv.bind("onPageReady", (arguments) -> {
            new Promise<>(() -> {
                // Or DB call in here.
                System.out.println("onPageReady called");
                long start = System.currentTimeMillis();
                countFolders(new File("C:\\"));
                long end = System.currentTimeMillis();
    
                System.out.println("done " + (end - start));
            }).await(); // Wait for completion.
            return null;
        });
```

**Comment by e3ndr** [comment]
@WanneSimon 
> I've got the same problem. I tried `cpp` code with [webview](https://github.com/webview/webview), it works properly. So I think it's caused by `jna` ( `native heap` limited ? ) .
> 
> I try to replace `jna` with `jnr` , but `webview_create` doesn't return the corrent pointer value.

would you mind forking with your JNR code and opening a PR? I'd be interested in testing it vs JNA.

**Comment by newk5** [comment]
> I meant this:
> 
> ```java
>         wv.bind("onPageReady", (arguments) -> {
>             new Promise<>(() -> {
>                 // Or DB call in here.
>                 System.out.println("onPageReady called");
>                 long start = System.currentTimeMillis();
>                 countFolders(new File("C:\\"));
>                 long end = System.currentTimeMillis();
>     
>                 System.out.println("done " + (end - start));
>             }).await(); // Wait for completion.
>             return null;
>         });
> ```

Just tried this, but same issue

**Comment by WanneSimon** [comment]
> @WanneSimon
> 
> > I've got the same problem. I tried `cpp` code with [webview](https://github.com/webview/webview), it works properly. So I think it's caused by `jna` ( `native heap` limited ? ) .
> > I try to replace `jna` with `jnr` , but `webview_create` doesn't return the corrent pointer value.
> 
> would you mind forking with your JNR code and opening a PR? I'd be interested in testing it vs JNA.

Sorry for too late to reply.
Here's my testing code ( `jnr` ). But it's not work properly!

[webview_java_jnr](https://github.com/WanneSimon/webview_java/blob/main-test/core/src/test/java/com/example/webview_java/ExampleJson.java)

**Comment by e3ndr** [comment]
> > I meant this:
> > ```java
> >         wv.bind("onPageReady", (arguments) -> {
> >             new Promise<>(() -> {
> >                 // Or DB call in here.
> >                 System.out.println("onPageReady called");
> >                 long start = System.currentTimeMillis();
> >                 countFolders(new File("C:\\"));
> >                 long end = System.currentTimeMillis();
> >     
> >                 System.out.println("done " + (end - start));
> >             }).await(); // Wait for completion.
> >             return null;
> >         });
> > ```
> 
> Just tried this, but same issue

Are you sure this code completes normally?

**Comment by e3ndr** [comment]
> > @WanneSimon
> > > I've got the same problem. I tried `cpp` code with [webview](https://github.com/webview/webview), it works properly. So I think it's caused by `jna` ( `native heap` limited ? ) .
> > > I try to replace `jna` with `jnr` , but `webview_create` doesn't return the corrent pointer value.
> > 
> > 
> > would you mind forking with your JNR code and opening a PR? I'd be interested in testing it vs JNA.
> 
> Sorry for too late to reply. Here's my testing code ( `jnr` ). But it's not work properly!
> 
> @e3ndr
> 
> [webview_java_jnr](https://github.com/WanneSimon/webview_java/blob/main-test/core/src/test/java/com/example/webview_java/ExampleJson.java)

Open a PR ;)

**Comment by newk5** [comment]
> > > I meant this:
> > > ```java
> > >         wv.bind("onPageReady", (arguments) -> {
> > >             new Promise<>(() -> {
> > >                 // Or DB call in here.
> > >                 System.out.println("onPageReady called");
> > >                 long start = System.currentTimeMillis();
> > >                 countFolders(new File("C:\\"));
> > >                 long end = System.currentTimeMillis();
> > >     
> > >                 System.out.println("done " + (end - start));
> > >             }).await(); // Wait for completion.
> > >             return null;
> > >         });
> > > ```
> > 
> > 
> > Just tried this, but same issue
> 
> Are you sure this code completes normally?

Yea everything works the same, I get no errors, no messages, no exceptions. Have you tried reproducing it with the code I posted above? It's very easy to reproduce, just increase the folderCountLimit until the issue happens.

**Comment by YairLevi** [comment]
Asking out of curiosity.
Why would the way java interacts with the native library cause issues when trying to interact with files, given that on cpp it works fine?

**Comment by newk5** [comment]
I dont know why it happens and I dont think its related to accessing disk files specifically, there's probably many other cases, but my reproducer seems to be the easiest way to reproduce the issue.

**Comment by e3ndr** [comment]
I cannot reproduce the issue.

I abridged the code for reproduction, but here's my exact code and it's result:
```java
public class ExampleRepro {

    public static void main(String[] args) {
        Webview wv = new Webview(true);

        wv.bind("test", (arguments) -> {
            countFolders(new File("C:\\"));
            return null;
        });

        wv.setTitle("Issue #17");
        wv.setSize(800, 600);

        wv.setHTML("<button onclick=\"test().then(() => alert('Done!'));\">Test</button>");

        wv.run();
        wv.close();
    }

    static int foldersCounted = 0;
    static int folderCountLimit = 8000;

    private static void countFolders(File dir) {
        if (foldersCounted > folderCountLimit) {
            return;
        }

        File[] lstFiles = dir.listFiles();
        if (lstFiles != null) {
            for (File file : lstFiles) {
                if (file.isDirectory()) {
                    foldersCounted++;
                    countFolders(file);
                }
            }
        }
    }

}
```

https://github.com/webview/webview_java/assets/33337309/38dd7020-d514-41c6-a8f2-dc3767cf3a32

**Comment by newk5** [comment]
This code is not doing the same thing. As I said above, the first call to java side on my code works too ( **onPageReady()** ), its the second call that fails ( **test()** ). Your code is only doing the first call. The code I posted shows the real issue. But I made a new reproducer for you, please just use this exact code:

```java
    public static void main(String[] args) {
        Webview wv = new Webview(true);

        wv.bind("test", (arguments) -> {
            System.out.println("TEST CALLED");
            countFolders(new File("C:\\"));
            return null;
        });

        wv.bind("test2", (arguments) -> {
            System.out.println("TEST2 CALLED");
            return null;
        });

        wv.setTitle("Issue #17");
        wv.setSize(800, 600);

         wv.setHTML("<button onclick=\"test().then(() => test2());\">Test</button>");

        wv.run();
        wv.close();
    }

    static int foldersCounted = 0;
    static int folderCountLimit = 9000;
    
    private static void countFolders(File dir) {
        if (foldersCounted > folderCountLimit) {
            return;
        }

        File[] lstFiles = dir.listFiles();
        if (lstFiles != null) {
            for (File file : lstFiles) {
                if (file.isDirectory()) {
                    foldersCounted++;
                    countFolders(file);
                }
            }
        }
    }

```
**test2() call never reaches the java side**, that is the issue. If the issue does not happen for you with this exact code, just increase the folderCountLimit until it does. (in this example I increased it to 9000 )

**Comment by e3ndr** [comment]
Was able to reproduce finally. Looks like WV just stops acknowledging calls to test2() entirely after the file counting test. I can't reproduce it using a sleep() nor a spin-wait so it might be a heap limitation.

Interestingly, using the new Bridge utility, it works perfectly fine (tested up to 30k folders):
```java
public class Issue17 {

    public static void main(String[] args) {
        Webview wv = new Webview(true);
        WebviewBridge bridge = new WebviewBridge(wv);

        bridge.defineObject("Test", new TestObject());

        wv.setTitle("Issue #17");
        wv.setSize(800, 600);

        wv.setHTML("<button onclick=\"Test.test1().then((count) => alert('test1 done ' + count)).then(() => Test.test2()).then(() => alert('test2 done'));\">Test</button>");

        wv.run();
        wv.close();
    }

    public static class TestObject extends JavascriptObject {

        static int foldersCounted = 0;
        static int folderCountLimit = 30_000;

        private static void countFolders(File dir) {
            if (foldersCounted > folderCountLimit) {
                return;
            }

            File[] lstFiles = dir.listFiles();
            if (lstFiles != null) {
                for (File file : lstFiles) {
                    if (file.isDirectory()) {
                        foldersCounted++;
                        countFolders(file);
                    }
                }
            }
        }

        @JavascriptFunction
        public int test1() {
            System.out.println("TEST1 CALLED");
            countFolders(new File("C:\\"));
            System.out.println("TEST1 RETURNED");
            return foldersCounted;
        }

        @JavascriptFunction
        public void test2() {
            System.out.println("TEST2 CALLED&RETURNED");
        }

    }

}
```


https://github.com/webview/webview_java/assets/33337309/2f44eb64-47fe-4c8d-bbbb-827c0847c433

**Comment by newk5** [comment]
Can confirm with the bridge the issue does not happen, even in my real application where Im doing db calls.

**Comment by e3ndr** [comment]
I would recommend using the Bridge then until this can be better debugged.
