### ISSUE TITLE
Doesn't run out of the box on Ubuntu (not found, then blank window)

### ISSUE THREAD

**Issue by mikedawson** [webview/webview_java#21]
I tried running the release (1.3.0) on Ubuntu 23.04. I have managed to make it show something now.

Expected behavior: 

Running example.java shows Google.com

Observed behavior:

First attempt: 

![Screenshot from 2024-01-28 22-40-45](https://github.com/webview/webview_java/assets/4280622/3f9179ba-38f4-4c24-959a-822399856e5d)

WebViewNative seems to put the .so file in the working directory, and its not found there. Seems like it needs to be under linux-x86-64/ in a the native search path. IIRC there is an argument that can be used to specify the search path, so that would be easy enough to overcome.

Second attempt:

Webview comes up blank. Seems to be related to this: https://groups.google.com/g/linux.debian.bugs.dist/c/jqFSXiFozd4

Setting the environment variable suggested on the thread there 

WEBKIT_DISABLE_DMABUF_RENDERER=1

Makes it work.

**Comment by e3ndr** [comment]
> I tried running the release (1.3.0) on Ubuntu 23.04. I have managed to make it show something now.
> 
> Expected behavior:
> 
> Running example.java shows Google.com
> 
> Observed behavior:
> 
> First attempt:
> 
> ![Screenshot from 2024-01-28 22-40-45](https://private-user-images.githubusercontent.com/4280622/300286765-3f9179ba-38f4-4c24-959a-822399856e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTA4NDUsIm5iZiI6MTcwNzI1MDU0NSwicGF0aCI6Ii80MjgwNjIyLzMwMDI4Njc2NS0zZjkxNzliYS0zOGY0LTRjMjQtOTU5YS04MjIzOTk4NTZlNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMjAxNTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzgwNzVmMjRlZWNmMWVmNjMxZTE1MmY5Zjk0ZWMzY2Y5NDEyNTNmZTJmNTA0YWM2YjM3OThmYWZhOWU1ZTNiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uxta7rtMoh_o9WvOagXl0g-f5AD1ZURuRedZRrAh244)
> 
> WebViewNative seems to put the .so file in the working directory, and its not found there. Seems like it needs to be under linux-x86-64/ in a the native search path. IIRC there is an argument that can be used to specify the search path, so that would be easy enough to overcome.
> 
> Second attempt:
> 
> Webview comes up blank. Seems to be related to this: https://groups.google.com/g/linux.debian.bugs.dist/c/jqFSXiFozd4
> 
> Setting the environment variable suggested on the thread there
> 
> WEBKIT_DISABLE_DMABUF_RENDERER=1
> 
> Makes it work.

Does doing `chmod +x libwebview.so` fix the library and allow the webview to start up?

**Comment by e3ndr** [comment]
Also, I just added some new loading logic in `84bd9ec`. Would you mind testing that commit?
