### ISSUE TITLE
Fix warning and error messages in BridgeScript.js

### ISSUE THREAD

**Issue by naxostech** [webview/webview_java#23]
NetBeans shows some warning messages in BridgeScript.js mostly because of the use of == and != instead of === and !==. « typeof » already returns a string, there is no need to perform an implicit conversion.

The problems are here :
https://github.com/webview/webview_java/blob/main/bridge/src/main/resources/dev/webview/webview_java/bridge/BridgeScript.js#L1 (return statement outside a function)
https://github.com/webview/webview_java/blob/main/bridge/src/main/resources/dev/webview/webview_java/bridge/BridgeScript.js#L13 (useless implicit conversion)
https://github.com/webview/webview_java/blob/main/bridge/src/main/resources/dev/webview/webview_java/bridge/BridgeScript.js#L87 (useless implicit conversion)
https://github.com/webview/webview_java/blob/main/bridge/src/main/resources/dev/webview/webview_java/bridge/BridgeScript.js#L97 (missing semicolon)

Those « problems » don’t prevent the project from working but maybe relying on such behaviours is a bad idea on a long term.

**Comment by e3ndr** [comment]
You're completely right. This was mostly ported from an existing project that was hacked together very jankily :P

Will fix & lint :)

**Comment by e3ndr** [comment]
Btw, for `return statement outside a function`, this code is actually run in a function. So return works as expected :)

**Comment by e3ndr** [comment]
I think this is finished. Comment back on this issue if you have any other concerns and I'll reopen :)

**Comment by naxostech** [comment]
Hello Alex,
Sorry for the delay of my answer and great thanks to have fixed the issues. 
If you have time and if possible, could you try to rewrite your code to remove the "return" (shown as warning in Netbeans).
Thanks in advance

**Comment by e3ndr** [comment]
The return is legal, as all JS code executed by WVJ is already in a function. Does Netbeans have a way to ignore a line of code so that we can clear that warning? Thanks.
