### ISSUE TITLE
Transparent background color

### ISSUE THREAD

**Issue by Osiris-Team** [webview/webview_java#7]
I think it's not currently possible to change this? It seems to be white.

**Comment by e3ndr** [comment]
You can try using the `createAWT()` helper, casting the result to `java.lang.Canvas` and then using the appropriate setColor method. However I do not know if the actual Webview library supports transparency.

**Comment by Osiris-Team** [comment]
@e3ndr Yeah that's exactly what I tried. I also made the backgrounds of all parent panels/layouts transparent + the actual body of the html page.

**Comment by e3ndr** [comment]
Looks like Webview doesn't support transparency. Closing this for now...
