### ISSUE TITLE
eval("console.log('hello world!')")  is not work 

### ISSUE THREAD

**Issue by fangyuchuang** [webview/webview_java#8]
wv.evall("console.log('hello world!')")   used by java.

public static void main(String[] args) {
        Webview wv = new Webview(true); // Can optionally be created with an AWT component to be painted on.

        // Calling `await echo(1,2,3)` will return `[1,2,3]`
        wv.bind("echo", (arguments) -> {
            return arguments;
        });

        wv.setTitle("My Webview App");
        wv.setSize(800, 600);

        String url = "file:\\\\C:\\mansiExe\\client\\device\\customer\\nwcn-touyinji\\html\\index.html";
        wv.loadURL(url);

        // Run the webview event loop, the webview is fully disposed when this returns.
        new Thread(new Runnable() {
            @Override
            public void run() {
                Scanner sc=new Scanner(System.in);
                String word;
                //定义while控制循环输入
                System.out.println("请输入任意内容（输入exit就退出，否则继续输入）：");
                while (true) {
                    //键盘接收数据
                    word=sc.nextLine();
                    //判断接收的数据是否为"exit"
                    wv.eval("console.log(11)} ");

                    if (word.equals("exit")) {
                        //如果是，提示退出输入
                        System.out.println("退出输入！");
                        //跳出循环
                        break;
                    }else {//如果不是，提示继续输入
                        System.out.println("请继续输入：");
                    }
                }
            }
        }).start();

        wv.run();
}

when i press anykey, the java log  can printf ,but the javascript is not ecxe.

**Comment by e3ndr** [comment]
You have a syntax error here:
`                wv.eval("console.log(11)} ");`
`                                        ^`

It should be:
`                wv.eval("console.log(11);");`

See if that fixes your issue.

**Comment by fangyuchuang** [comment]
thank your reply, i am sorry for making the mistake code, but i try again by the correct code , it can not work correct.  you can try the example below. 

import dev.webview.Webview;
import java.util.Scanner;

public class Example {
    public static void main(String[] args) {
        Webview wv = new Webview(true); // Can optionally be created with an AWT component to be painted on.

        // Calling `await echo(1,2,3)` will return `[1,2,3]`
        wv.bind("echo", (arguments) -> {
            return arguments;
        });

        wv.setTitle("My Webview App");

        wv.setSize(800, 600);
        wv.loadURL("http://www.google.com");
        new Thread(new Runnable() {
            @Override
            public void run() {
                Scanner scanner = new Scanner(System.in);
                System.out.print("input a num: ");
                while (true) {
                    int num1 = scanner.nextInt();
                    switch (num1) {
                        case 1:
                            wv.eval("console.log('hello world!')");
                            wv.eval("window.alert('hello world!')");
                            System.out.println("1 is press");
                            break;
                        default:
                            System.out.println("default");
                    }
                }
            }
        }).start();
        // Run the webview event loop, the webview is fully disposed when this returns.

        wv.run();
    }

}

**Comment by fangyuchuang** [comment]
is the webview.dll will call the edge api， if so,   can i reinstall some difference edge version to try?

**Comment by e3ndr** [comment]
> is the webview.dll will call the edge api， if so, can i reinstall some difference edge version to try?

You will need the latest Edge and WebView2 Runtime installed.

**Comment by Osiris-Team** [comment]
@fangyuchuang After loadURL() add Thread.sleep(10)

**Comment by newk5** [comment]
Same issue here. I even tried to delay calling .eval until the webview fully initialized. I also tried it inside a .bind() lambda but it doesn't seem to be working

**Comment by newk5** [comment]
Ok after more testing I noticed the following:

Calling **webview.eval()** after  **webview.run()** will never work unless its inside a **webview.bind()** lambda, this works if you load a URL from disk (file://) or from somewhere on the web (http://). However if loading a url made from data URL, webview.eval will never work in any ocasion. 

This is the code I'm using to convert my html to a base64 data URL 

```java
  public void loadHTML(String html) {
        String c = "data:text/html;base64,%s".formatted(Base64.getEncoder().encodeToString(html.getBytes()));
        webview.loadURL(c);
    }
```
